// let state = ...
// let state_to_ui = ...
// let on_key_down = ...

const svgNS = "http://www.w3.org/2000/svg"

// TODO: Improve user experience of consuming JS objects generated by the JS emitter

function create_svg_elem(elem) {
  switch (elem.variant) {
    case 0:
      const line = document.createElementNS(svgNS, "line")
      line.setAttribute("x1", elem.field0)
      line.setAttribute("y1", elem.field1)
      line.setAttribute("x2", elem.field2)
      line.setAttribute("y2", elem.field3)
      line.setAttribute("stroke-width", elem.field4)
      line.setAttribute("stroke", elem.field5)
      return line
  }
}

function create_html_elem(elem) {
  switch (elem.variant) {
    case 0:
      const button = document.createElement("button")
      button.onclick = () => {
        state = elem.field1(state)
        render_ui()
      }
      for (const child of elem.field0) {
        button.appendChild(create_html_elem(child))
      }
      return button
    case 1:
      const div = document.createElement("div")
      div.setAttribute("style", elem.field0)
      for (const child of elem.field1) {
        div.appendChild(create_html_elem(child))
      }
      return div
    case 2:
      return document.createTextNode(elem.field0)
    case 3:
      const svg = document.createElementNS(svgNS, "svg")
      svg.setAttribute("style", elem.field0)
      svg.setAttribute("viewBox", `0 0 ${elem.field1} ${elem.field2}`)
      for (const child of elem.field3) {
        svg.appendChild(create_svg_elem(child))
      }
      return svg
  }
}

function render_ui() {
  ui = state_to_ui(state)
  document.body.innerHTML = ""
  document.title = ui.field0
  for (const elem of ui.field1) {
    document.body.appendChild(create_html_elem(elem))
  }
}

window.onkeydown = (e) => {
  state = on_key_down(state, {field0: e.key})
  render_ui()
}

window.onload = () => {
  render_ui()
}
